Repository xuri/xgen, pull requests merged in 2025-06, with the labels that each got.

#94 Breaking changes, Go 1.23.0 and later required for upgrade of dependency package `golang.org/x/net`
  .github/workflows/go.yml
  README.md
  README_zh.md
  cmd/xgen/xgen.go
  genJava.go
  genRust.go
  genTypeScript.go
  go.mod
  go.sum
  utils.go
  xmlChoice.go
  xmlExtension.go
Labels: size/M

#87 This fixes #86, Duplicated field in the generated code
  xmlElement.go
Labels: size/XS

#84 Do not use the outdated extern crate macro for importing dependencies
  genRust.go
  test/rs/base64.xsd.rs
Labels: size/XS

#81 Support for optional element
  genGo.go
  test/go/base64.xsd.go
  test/rs/base64.xsd.rs
  xmlElement.go
Labels: size/S
